@startuml 'data_bank'
entity regions {
    *region_id : int
    --
    *region_name : varchar(20)
}

entity customer_nodes {
    *customer_id : int
    --
    *region_id : int
    --
    *node_id : int
    --
    *star_date : date
    --
    *end_date : date
}

entity customer_transactions {
 *customer_id : int
 --
 *txn_date : date
 --
 *txn_type : varchar (20)
 --
 *txn_amount : int

}

regions ||--|{ customer_nodes : one to many
customer_nodes ||--|{ customer_transactions : one to many

@enduml